/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tharikh
 */
public class NurseMedicine extends javax.swing.JFrame {

    /**
     * Creates new form NurseMedicine
     */
    Connection con=null;
    String patid;
    public NurseMedicine() {
        initComponents();
    }
    public NurseMedicine(String patid){
        this();
        this.patid=patid;
        display();
    }
    private void display(){
        medicine();
        lab();
        
    }
    void lab(){
        con=DashBoard.conn;
        int i=0;
        name.setText("Patient ID -"+patid);
        String query="SELECT * from labPatient inner join checkup on labPatient.cid=checkup.cid inner join Lab on labPatient.labid=Lab.labid where pid=? order by date desc";
        try{
        PreparedStatement stm=con.prepareStatement(query);
        stm.setString(1,patid);
        ResultSet rs=stm.executeQuery();
        String colname[]={"Lab id","checkup date","Lab name"};
        String [][]data;
        rs.last();
        data=new String[rs.getRow()][3];
        rs.beforeFirst();
        while(rs.next()){
            data[i][0]=rs.getString("labid");
            data[i][1]=rs.getString("date");
            data[i][2]=rs.getString("test");
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(data, colname);
        labtable.setModel(model);
                }catch(Exception e){System.out.println(e.getMessage());}
    }
    void medicine(){
        con=DashBoard.conn;
        int i=0;
        name.setText("Patient ID -"+patid);
        String query="SELECT * from check_med inner join checkup on check_med.checkid=checkup.cid inner join medicine on check_med.mid=medicine.mid where pid=? order by date desc";
        try{
        PreparedStatement stm=con.prepareStatement(query);
        stm.setString(1,patid);
        ResultSet rs=stm.executeQuery();
        String colname[]={"medicine id","checkup date","medicine name"};
        String [][]data;
        rs.last();
        data=new String[rs.getRow()][3];
        rs.beforeFirst();
        while(rs.next()){
            data[i][0]=rs.getString("mid");
            data[i][1]=rs.getString("date");
            data[i][2]=rs.getString("mname");
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(data, colname);
        medtable.setModel(model);
                }catch(Exception e){System.out.println(e.getMessage());}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        medtext = new javax.swing.JTabbedPane();
        medtab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medtable = new javax.swing.JTable();
        labtab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(175, 116, 251));

        name.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(1, 1, 1));
        name.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        medtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(medtable);

        javax.swing.GroupLayout medtabLayout = new javax.swing.GroupLayout(medtab);
        medtab.setLayout(medtabLayout);
        medtabLayout.setHorizontalGroup(
            medtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        medtabLayout.setVerticalGroup(
            medtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medtabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        medtext.addTab("Medicine", medtab);

        labtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(labtable);

        javax.swing.GroupLayout labtabLayout = new javax.swing.GroupLayout(labtab);
        labtab.setLayout(labtabLayout);
        labtabLayout.setHorizontalGroup(
            labtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        labtabLayout.setVerticalGroup(
            labtabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labtabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        medtext.addTab("Lab Details", labtab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medtext)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medtext))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NurseMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NurseMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NurseMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NurseMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NurseMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel labtab;
    private javax.swing.JTable labtable;
    private javax.swing.JPanel medtab;
    private javax.swing.JTable medtable;
    private javax.swing.JTabbedPane medtext;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
